### ISSUE TITLE
Неверное место для определения

### ISSUE THREAD

**Issue by Garuda-1** [dzhiblavi/calculus#10]
Градиент используется до его определения, разумно его переместить до первого упоминания (стр. 9).

https://github.com/dzhiblavi/calculus/blob/35af5d85b976c93fcfb11a6d8215369f2bdd10a8/calculus-III/section_2.tex#L357-L367

**Comment by dzhiblavi** [comment]
исправил

**Comment by Garuda-1** [comment]
Подтверждаю.
