### ISSUE TITLE
I think, X instead of E. At least, I haven't seen any E below and above

### ISSUE THREAD

**Issue by Deletrius366** [dzhiblavi/calculus#15]
https://github.com/dzhiblavi/calculus/blob/9d3a86f055c8c745f7bec86193e700ab707d2a81/calculus-III/section_6.tex#L193

**Comment by dzhiblavi** [comment]
Принято

**Comment by dzhiblavi** [comment]
Исправил

**Comment by dzhiblavi** [comment]
Закрываю, так как исправил
