### ISSUE TITLE
Неверная переменная

### ISSUE THREAD

**Issue by Garuda-1** [dzhiblavi/calculus#16]
Вероятно, имелось в виду, что ф принадлежит C^r.

https://github.com/dzhiblavi/calculus/blob/3543e40d331578ac0cffef007ebeff8a81912fe5/calculus-III/section_4.tex#L310

**Comment by dzhiblavi** [comment]
Принял

**Comment by dzhiblavi** [comment]
Исправил

**Comment by Garuda-1** [comment]
source.pdf не обновился.

**Comment by dzhiblavi** [comment]
Обновил

**Comment by Garuda-1** [comment]
Подтверждаю.
