### ISSUE TITLE
Неверная размерность

### ISSUE THREAD

**Issue by Garuda-1** [dzhiblavi/calculus#17]
Видимо, имелось в виду, что S(x, 0) = (x, H(x, 0))

https://github.com/dzhiblavi/calculus/blob/3543e40d331578ac0cffef007ebeff8a81912fe5/calculus-III/section_4.tex#L318

**Comment by dzhiblavi** [comment]
Принял

**Comment by dzhiblavi** [comment]
Исправил

**Comment by Garuda-1** [comment]
Подтверждаю.
