### ISSUE TITLE
Index fix

### ISSUE THREAD

**Issue by IvanMaslov** [dzhiblavi/calculus#2]
https://github.com/dzhiblavi/mathematical_analysis/blob/46d2b95f2484438905e0178e8fa45bb6c9607e96/mathan-III/section_1.tex#L81

**Comment by IvanMaslov** [comment]
\norm{\x}_1 \geqslant 
И 2 строчками ниже тоже

**Comment by dzhiblavi** [comment]
Индекс относится к норме, тут все ок вроде бы
