### ISSUE TITLE
Алгебраическая ошибка

### ISSUE THREAD

**Issue by Garuda-1** [dzhiblavi/calculus#22]
Вероятно, после первого равенства коэффициент должен быть n, не 1/n.

https://github.com/dzhiblavi/calculus/blob/f691d5c2ab39aaaef13e4ba63169dc6005664d59/calculus-III/section_6.tex#L279-L283

**Comment by dzhiblavi** [comment]
Принял, исправил

**Comment by Garuda-1** [comment]
Подтверждаю.
