### ISSUE TITLE
Алгебраические ошибки

### ISSUE THREAD

**Issue by Garuda-1** [dzhiblavi/calculus#27]
![59e3840ab4e79666657406](https://user-images.githubusercontent.com/18511260/71782639-81396b80-2fed-11ea-96b4-172119eaea93.jpeg)

https://github.com/dzhiblavi/calculus/blob/29fd557ac505042aa4ab7d95dd20a641caf34a6e/calculus-III/section_7.tex#L322-L324

**Comment by Garuda-1** [comment]
1) Производная частного
2) Знаменатель второй дроби вроде имеет степень "s + 1"

**Comment by Deletrius366** [comment]
Только хотел отметить)

**Comment by dzhiblavi** [comment]
принял

**Comment by Garuda-1** [comment]
Подтверждаю.
