### ISSUE TITLE
Неверное определение

### ISSUE THREAD

**Issue by Garuda-1** [dzhiblavi/calculus#29]
Строго говоря, из данного определения произведение путей задано на [a, b + d - c].

https://github.com/dzhiblavi/calculus/blob/29fd557ac505042aa4ab7d95dd20a641caf34a6e/calculus-III/section_8.tex#L33

**Comment by dzhiblavi** [comment]
Да и нестрого тоже

**Comment by Garuda-1** [comment]
Подтверждаю.
