### ISSUE TITLE
Неверный макрос

### ISSUE THREAD

**Issue by Garuda-1** [dzhiblavi/calculus#32]
Видимо, тут должно быть доказательство, не определение.

https://github.com/dzhiblavi/calculus/blob/56e4f042ec3c3973661fea0016b0e82e90d31171/calculus-III/section_8.tex#L227-L233

**Comment by dzhiblavi** [comment]
Это исправлено в af73afa (#30)

**Comment by Garuda-1** [comment]
Подтверждаю.
