### ISSUE TITLE
Неочевидные переходы в разделе про меру Лебега

### ISSUE THREAD

**Issue by Garuda-1** [dzhiblavi/calculus#41]
Следующие места нуждаются в пояснениях:

 - Из чего это следует?
https://github.com/dzhiblavi/calculus/blob/1fea4a202e7bdff18bd7b14fe0370d5f632f5b80/calculus-III/section_9.tex#L401

 - Как это следует из доказательства?
https://github.com/dzhiblavi/calculus/blob/1fea4a202e7bdff18bd7b14fe0370d5f632f5b80/calculus-III/section_9.tex#L412-L413

 - Как из того, что мы накрыли E множествами, которые разбиваются на ячейки, следует, что их объединение разбивается на ячейки? Видимо, нужно указать, что мера E меньше суммы по отдельности мер каждого из множества покрытия, и что ячейки с нужными свойствами можно получить из того, что объединение открытых открыто.
https://github.com/dzhiblavi/calculus/blob/1fea4a202e7bdff18bd7b14fe0370d5f632f5b80/calculus-III/section_9.tex#L463-L464

 - Стоит упомянуть, что эти множества взяты из прошлой теоремы.
https://github.com/dzhiblavi/calculus/blob/1fea4a202e7bdff18bd7b14fe0370d5f632f5b80/calculus-III/section_9.tex#L619-L620

 - Возможно, стоит уточнить, почему в теореме B и C именно борелевские.
https://github.com/dzhiblavi/calculus/blob/1fea4a202e7bdff18bd7b14fe0370d5f632f5b80/calculus-III/section_9.tex#L615-L616

 - Вероятно, нужно чуть больше описания доказательства, потому что не совсем ясно, как унаследоваться от этого доказательства, а также неясно, что делать все же с запретом на объединения и пересечения.
https://github.com/dzhiblavi/calculus/blob/1fea4a202e7bdff18bd7b14fe0370d5f632f5b80/calculus-III/section_9.tex#L713-L716

 - Вероятно, нужно указать, что измеримые множества и меры Лебега в R^n и R^m -- разные вещи.
https://github.com/dzhiblavi/calculus/blob/1fea4a202e7bdff18bd7b14fe0370d5f632f5b80/calculus-III/section_9.tex#L718-L721

 - Думаю, тут нужна картинка.
https://github.com/dzhiblavi/calculus/blob/1fea4a202e7bdff18bd7b14fe0370d5f632f5b80/calculus-III/section_9.tex#L776-L785

**Comment by dzhiblavi** [comment]
- Добавил пояснение.

- Выделил жирным в доказательстве.

- Если мы накрыли E по частям ячейками, то мы накрыли и само Е ячейками (достаточно взять объединение всех покрытий) [нам нигде не нужна дизъюнктность]. Неравенство -- счетная полуаддитивность.

- Упомянул.

- https://github.com/dzhiblavi/calculus/blob/1fea4a202e7bdff18bd7b14fe0370d5f632f5b80/calculus-III/section_9.tex#L628-L629

- Передоказал.

- Указал.

- Добавил картинку.
